apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: poc-app
  template:
    metadata:
      labels:
        app: poc-app
    spec:
      containers:
        - name: poc-app
          image: poc-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
